branch-defaults:
  default:
    environment: googleMapsParameter
  master:
    environment: googleMapsParameter
global:
  application_name: google-maps-parameters
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.6
  default_region: us-west-2
  profile: eb-cli
  sc: null
